#!/usr/bin/env python3
"""Attach zh labels to every lexicon tag."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEX = ROOT / "web" / "lexicon.json"

ZH = {
    "1boy": "1個男性",
    "1girl": "1個女性",
    "2boys": "2個男性",
    "2girls": "2個女性",
    "3boys": "3個男性",
    "3girls": "3個女性",
    "4girls": "4個女性",
    "69": "69式",
    "abs": "腹肌",
    "absurdly long hair": "超長髮",
    "absurdres": "超高解析",
    "adam's apple": "喉結",
    "adjusting clothes": "整理衣服",
    "adjusting hair": "整理頭髮",
    "adult": "成人",
    "after sex": "事後",
    "after vaginal": "插入事後",
    "against glass": "靠著玻璃",
    "against wall": "靠牆",
    "ahegao": "阿嘿顏",
    "ahoge": "呆毛",
    "all fours": "趴跪",
    "alley": "巷弄",
    "amazing quality": "極致品質",
    "amazon position": "女上位壓制",
    "amber eyes": "琥珀眼",
    "anal": "肛交",
    "ancient greek clothes": "古希臘服",
    "anilingus": "舔肛",
    "apron": "圍裙",
    "aqua eyes": "水色眼",
    "aqua hair": "水色髮",
    "arched back": "弓背",
    "areola slip": "乳暈走光",
    "areolae": "乳暈",
    "armor": "鎧甲",
    "armpits": "腋下",
    "arms behind back": "雙手背後",
    "arms behind head": "雙手腦後",
    "aroused": "情動",
    "ass focus": "臀部特寫",
    "ass grab": "抓臀",
    "ass visible through thighs": "腿間可見臀",
    "averting eyes": "避開視線",
    "babydoll": "娃娃裝睡衣",
    "backlighting": "逆光",
    "bags under eyes": "眼袋",
    "balcony": "陽台",
    "bangs": "瀏海",
    "bar (place)": "酒吧",
    "bara": "筋肉男",
    "barefoot": "赤腳",
    "bath": "浴場",
    "bathrobe": "浴袍",
    "bathroom": "浴室",
    "bathtub": "浴缸",
    "beach": "海邊",
    "beard": "鬍鬚",
    "beckoning": "招手",
    "bed": "床",
    "bedroom": "臥室",
    "bent over": "彎腰",
    "best quality": "最高品質",
    "between breasts": "乳溝之間",
    "between thighs": "大腿之間",
    "bikini": "比基尼",
    "biting own lip": "咬唇",
    "black hair": "黑髮",
    "blonde hair": "金髮",
    "blouse": "襯衫（女）",
    "blue eyes": "藍眼",
    "blue hair": "藍髮",
    "blunt bangs": "齊瀏海",
    "blush": "臉紅",
    "bob cut": "短鮑伯頭",
    "body blush": "全身潮紅",
    "body freckles": "身上雀斑",
    "bodysuit": "連身緊身衣",
    "bokeh": "散景",
    "boots": "靴子",
    "bottomless": "下身裸",
    "bowtie": "蝴蝶結領結",
    "boxers": "平口內褲",
    "bra": "胸罩",
    "bra pull": "拉下胸罩",
    "bracelet": "手鍊",
    "braid": "辮子",
    "breast focus": "胸部特寫",
    "breast grab": "抓胸",
    "breast hold": "托胸",
    "breast sucking": "吸吮乳房",
    "briefs": "三角褲",
    "broad shoulders": "寬肩",
    "brown eyes": "棕眼",
    "brown hair": "棕髮",
    "bulge": "鼓起",
    "business suit": "商務套裝",
    "cafe": "咖啡廳",
    "cameltoe": "駱駝趾",
    "camisole": "細肩帶背心",
    "candlelight": "燭光",
    "car interior": "車內",
    "castle": "城堡",
    "caught": "被撞見",
    "chainmail": "鎖子甲",
    "changing room": "更衣室",
    "cheerleader": "啦啦隊服",
    "cherry blossoms": "櫻花",
    "chest hair": "胸毛",
    "chinese architecture": "中式建築",
    "chinese clothes": "中式服裝",
    "choker": "頸環",
    "chromatic aberration": "色差",
    "cinematic lighting": "電影光",
    "city": "城市",
    "cityscape": "都市風景",
    "classroom": "教室",
    "cleavage": "乳溝",
    "close-up": "特寫",
    "clothed sex": "著衣性交",
    "clothes between breasts": "衣服夾在胸間",
    "clothes lift": "掀起衣服",
    "clothes pull": "拉扯衣服",
    "clothes tug": "拽衣服",
    "clothing aside": "撥開衣物",
    "collar": "項圈",
    "collarbone": "鎖骨",
    "colored inner hair": "內層彩髮",
    "come hither": "勾人過來",
    "completely nude": "全裸",
    "contrapposto": "對立式平衡站姿",
    "corset": "束腰",
    "couch": "沙發",
    "covering breasts": "遮胸",
    "covering crotch": "遮下體",
    "covering own mouth": "摀嘴",
    "cowboy shot": "七分身",
    "cowgirl position": "騎乘位",
    "crawling": "爬行",
    "creampie": "中出",
    "crop top": "短版上衣",
    "crossed arms": "雙手交叉",
    "crossed legs": "翹腿",
    "cuddling": "依偎",
    "cum": "精液",
    "cum in mouth": "口內射精",
    "cum in pussy": "內射",
    "cum on body": "射在身上",
    "cum on breasts": "射在胸部",
    "cumdrip": "精液滴落",
    "cunnilingus": "舔陰",
    "curly hair": "捲髮",
    "curvy": "曲線身材",
    "dancing": "跳舞",
    "dark skin": "深膚色",
    "dark-skinned female": "深膚色女性",
    "dark-skinned male": "深膚色男性",
    "day": "白天",
    "deepthroat": "深喉",
    "depth of field": "景深",
    "dim lighting": "昏暗光線",
    "doggystyle": "背後位",
    "double bun": "雙髮髻",
    "double penetration": "雙重插入",
    "downblouse": "領口走光",
    "dress": "洋裝",
    "dress lift": "掀裙",
    "drill hair": "鑽捲髮",
    "dusk": "黃昏",
    "earrings": "耳環",
    "east asian architecture": "東亞建築",
    "ejaculation": "射精",
    "elbow gloves": "過肘手套",
    "elevator": "電梯",
    "embarrassed": "害羞",
    "erection": "勃起",
    "erection under clothes": "衣內勃起",
    "evening": "傍晚",
    "evening gown": "晚禮服",
    "exhibitionism": "露出",
    "explicit": "露骨",
    "eye contact": "對視",
    "eyelashes": "睫毛",
    "eyeshadow": "眼影",
    "facesitting": "坐臉",
    "facial": "顏射",
    "facial hair": "鬍渣／鬍鬚",
    "facing away": "背對",
    "fellatio": "口交",
    "female ejaculation": "潮吹",
    "female masturbation": "女性自慰",
    "film grain": "膠片顆粒",
    "finger to mouth": "手指抵唇",
    "fingering": "手指插入",
    "fishnet thighhighs": "網襪過膝",
    "fishnets": "網襪",
    "fitting room": "試衣間",
    "flashing": "走光／閃露",
    "floating hair": "髮絲飄起",
    "fog": "霧",
    "footjob": "足交",
    "forest": "森林",
    "freckles": "雀斑",
    "french kiss": "法式深吻",
    "frills": "荷葉邊",
    "from above": "俯視",
    "from behind": "從後方",
    "from below": "仰視",
    "from side": "側面",
    "fucked silly": "被幹到失神",
    "full body": "全身",
    "full nelson": "鎖頸體位",
    "fundoshi": "褌",
    "futon": "日式床墊",
    "gakuran": "學生制服（男）",
    "garden": "庭園",
    "garter belt": "吊襪帶",
    "geta": "木屐",
    "gigantic breasts": "超巨乳",
    "glasses": "眼鏡",
    "gloves": "手套",
    "goatee": "山羊鬍",
    "gothic architecture": "哥德建築",
    "gown": "長禮服",
    "gradient hair": "漸層髮色",
    "green eyes": "綠眼",
    "green hair": "綠髮",
    "grey eyes": "灰眼",
    "grey hair": "灰髮",
    "grinding": "磨蹭",
    "guided penetration": "引導插入",
    "gym uniform": "體操服",
    "hair between eyes": "髮絲過眼間",
    "hair bun": "髮髻",
    "hair ornament": "髮飾",
    "hair over one eye": "髮遮一眼",
    "hair over shoulder": "髮披肩",
    "hakama": "袴",
    "half-closed eyes": "半閉眼",
    "hallway": "走廊",
    "hand in panties": "手伸進內褲",
    "hand in pocket": "手插口袋",
    "hand on hip": "手叉腰",
    "hand on own ass": "手撫自己臀部",
    "hand on own chest": "手按胸口",
    "hand on own crotch": "手按下體",
    "hand on own hip": "手叉自己的腰",
    "handjob": "手交",
    "hands on own breasts": "雙手捧胸",
    "hands on own hips": "雙手叉腰",
    "hanfu": "漢服",
    "hanging breasts": "懸垂乳房",
    "happy sex": "愉悅性交",
    "hat": "帽子",
    "head tilt": "歪頭",
    "heart hands": "比心手勢",
    "heavy breathing": "喘息",
    "heterochromia": "異色瞳",
    "high heels": "高跟鞋",
    "high ponytail": "高馬尾",
    "highres": "高解析",
    "hime cut": "姬髮式",
    "hoodie": "連帽衫",
    "hotel room": "飯店房間",
    "hug": "擁抱",
    "hug from behind": "從後擁抱",
    "huge ass": "巨臀",
    "huge breasts": "巨乳",
    "huge penis": "巨大陰莖",
    "imminent penetration": "即將插入",
    "index fingers together": "食指對碰",
    "indian style": "盤腿坐",
    "indoors": "室內",
    "irrumatio": "強制口交",
    "jack-o' challenge": "Jack-O 挑戰姿勢",
    "jacket": "外套",
    "japanese armor": "和風鎧甲",
    "japanese clothes": "和服類",
    "jeans": "牛仔褲",
    "jewelry": "珠寶",
    "kimono": "着物",
    "kiss": "接吻",
    "kissing": "接吻中",
    "kitchen": "廚房",
    "kneehighs": "及膝襪",
    "kneeling": "跪著",
    "knight": "騎士",
    "lab coat": "實驗衣",
    "lamp": "燈",
    "large breasts": "大胸",
    "large penis": "大陰莖",
    "latex": "乳膠衣",
    "laurel crown": "月桂冠",
    "leaning back": "後仰",
    "leaning forward": "前傾",
    "legs up": "抬腿",
    "leotard": "連身緊身衣（體操）",
    "library": "圖書館",
    "licking lips": "舔唇",
    "lingerie": "內衣套裝",
    "lipstick": "口紅",
    "living room": "客廳",
    "locker room": "更衣室（置物櫃）",
    "long eyelashes": "長睫毛",
    "long hair": "長髮",
    "long legs": "長腿",
    "looking at another": "看向他人",
    "looking at viewer": "看向觀眾",
    "looking back": "回眸",
    "looking down": "俯看",
    "looking to the side": "看向一側",
    "looking up": "仰看",
    "love hotel": "愛情旅館",
    "lying": "躺著",
    "m legs": "M字開腿",
    "maid": "女僕",
    "makeup": "化妝",
    "male masturbation": "男性自慰",
    "male underwear": "男性內褲",
    "mansion": "宅邸",
    "marble": "大理石",
    "masterpiece": "傑作",
    "masturbation": "自慰",
    "masturbation through clothes": "隔衣自慰",
    "mating press": "交配壓制",
    "mature female": "成熟女性",
    "mature male": "成熟男性",
    "medium breasts": "中等胸部",
    "medium hair": "中長髮",
    "messy hair": "凌亂頭髮",
    "micro bikini": "微型比基尼",
    "microskirt": "超短裙",
    "midriff": "腰腹",
    "miko": "巫女",
    "milf": "熟女",
    "miniskirt": "迷你裙",
    "missionary": "正常位",
    "modern": "現代",
    "mole": "痣",
    "mole under eye": "眼下痣",
    "moonlight": "月光",
    "multiple boys": "多名男性",
    "multiple girls": "多名女性",
    "muscular": "肌肉發達",
    "muscular female": "筋肉女性",
    "muscular male": "筋肉男性",
    "mustache": "鬍髭",
    "nail polish": "指甲油",
    "naked apron": "裸圍裙",
    "naked shirt": "只穿襯衫",
    "naked sweater": "只穿毛衣",
    "naked towel": "只裹毛巾",
    "narrow waist": "細腰",
    "naughty face": "下流表情",
    "navel": "肚臍",
    "navel piercing": "肚臍環",
    "necklace": "項鍊",
    "necktie": "領帶",
    "neon lights": "霓虹燈",
    "night": "夜晚",
    "nightgown": "睡袍",
    "nipple slip": "乳頭走光",
    "nipple tweak": "捏乳頭",
    "nipples": "乳頭",
    "no bra": "沒穿胸罩",
    "no panties": "沒穿內褲",
    "nsfw": "限制級",
    "nude": "裸體",
    "obi": "腰帶（和服）",
    "ocean": "海洋",
    "off shoulder": "露肩",
    "office": "辦公室",
    "ojou-sama pose": "大小姐姿勢",
    "on back": "仰躺",
    "on one knee": "單膝跪",
    "on side": "側躺",
    "on stomach": "趴著",
    "one breast out": "露出一邊胸部",
    "one knee up": "單膝抬起",
    "one-piece swimsuit": "連身泳裝",
    "onsen": "溫泉",
    "open clothes": "衣服敞開",
    "open jacket": "外套敞開",
    "open kimono": "和服敞開",
    "open mouth": "張嘴",
    "open shirt": "襯衫敞開",
    "orange eyes": "橙眼",
    "orange hair": "橙髮",
    "orgasm": "高潮",
    "outdoors": "室外",
    "overcast": "陰天",
    "pagoda": "塔",
    "paizuri": "乳交",
    "paizuri gesture": "乳交手勢",
    "paizuri under clothes": "隔衣乳交",
    "pajamas": "睡衣",
    "palace": "宮殿",
    "pale skin": "白皙皮膚",
    "panties": "內褲",
    "panties aside": "內褲撥開",
    "panting": "喘氣",
    "pants": "長褲",
    "pants pull": "拉下褲子",
    "panty pull": "拉下內褲",
    "pantyhose": "褲襪",
    "park": "公園",
    "parted lips": "微張的唇",
    "pectorals": "胸肌",
    "pencil skirt": "窄裙",
    "penis": "陰莖",
    "pillar": "柱子",
    "pink eyes": "粉眼",
    "pink hair": "粉髮",
    "pinned down": "被壓住",
    "pixie cut": "精靈短髮",
    "plate armor": "板甲",
    "playboy bunny": "兔女郎",
    "pleated skirt": "百褶裙",
    "plump": "豐滿",
    "pointing at viewer": "指向觀眾",
    "ponytail": "馬尾",
    "pool": "泳池",
    "poolside": "池邊",
    "portrait": "胸像構圖",
    "pov": "第一人稱視角",
    "presenting": "展示身體",
    "presenting ass": "展示臀部",
    "profile": "側臉",
    "prone bone": "俯臥後入",
    "pubic hair": "陰毛",
    "public sex": "公開場合性交",
    "puffy nipples": "腫脹乳頭",
    "purple eyes": "紫眼",
    "purple hair": "紫髮",
    "pussy": "陰部",
    "pussy focus": "陰部特寫",
    "pussy juice": "愛液",
    "qipao": "旗袍",
    "rain": "雨",
    "reaching towards viewer": "伸手向觀眾",
    "reclining": "倚靠躺",
    "red eyes": "紅眼",
    "red hair": "紅髮",
    "red nails": "紅指甲",
    "revealing clothes": "暴露的衣服",
    "reverse cowgirl position": "反向騎乘",
    "rolling eyes": "翻白眼",
    "rooftop": "屋頂",
    "ruins": "遺跡",
    "ruqun": "襦裙",
    "sagging breasts": "下垂胸部",
    "sailor dress": "水手服洋裝",
    "sandals": "涼鞋",
    "sauna": "三溫暖",
    "scar": "疤痕",
    "school swimsuit": "死庫水",
    "school uniform": "學生制服",
    "seductive smile": "誘惑的笑",
    "see-through clothes": "透視衣服",
    "seiza": "正坐",
    "self fondling": "自我愛撫",
    "serafuku": "水手服",
    "sex": "性交",
    "sex from behind": "從後插入",
    "shadow": "陰影",
    "shiny skin": "有光澤的皮膚",
    "shirt": "襯衫",
    "shirt lift": "掀起襯衫",
    "shoji": "障子",
    "short dress": "短洋裝",
    "short hair": "短髮",
    "short shorts": "熱褲",
    "shorts": "短褲",
    "shower (place)": "淋浴間",
    "shrine": "神社",
    "shy": "羞澀",
    "side ponytail": "側馬尾",
    "sidelighting": "側光",
    "sidelocks": "鬢髮",
    "silver hair": "銀髮",
    "sitting": "坐著",
    "sitting on lap": "坐在腿上",
    "skinny": "纖瘦",
    "skirt": "裙子",
    "skirt lift": "掀裙",
    "skyscraper": "摩天樓",
    "sleeping": "睡著",
    "slingshot swimsuit": "彈弓泳裝",
    "small breasts": "貧乳",
    "smile": "微笑",
    "light smile": "淺笑",
    "expressionless": "面無表情",
    "frown": "皺眉",
    "pout": "嘟嘴",
    "angry": "生氣",
    "sad": "悲傷",
    "crying": "哭泣",
    "drooling": "流口水",
    "moaning": "呻吟",
    "clenched teeth": "咬牙",
    "sparkling eyes": "閃亮的眼睛",
    "empty eyes": "空洞的眼睛",
    "sleepy": "睏倦",
    "serious": "嚴肅",
    "happy": "開心",
    "surprised": "驚訝",
    "scared": "害怕",
    "smug": "得意",
    "nervous": "緊張",
    "dutch angle": "荷蘭角",
    "fisheye": "魚眼",
    "wide shot": "遠景",
    "extreme close-up": "大特寫",
    "over shoulder": "過肩鏡頭",
    "from outside": "從外面看",
    "lower body": "下半身",
    "straight-on": "正面平視",
    "head out of frame": "頭在畫面外",
    "feet out of frame": "腳在畫面外",
    "looking away": "看向別處",
    "looking ahead": "向前看",
    "sideways glance": "側眼一瞥",
    "looking at breasts": "看著胸部",
    "sneakers": "運動鞋",
    "snow": "雪",
    "socks": "襪子",
    "soft lighting": "柔光",
    "solo": "單人",
    "spitroast": "兩端夾擊",
    "spooning": "湯匙體位",
    "spotlight": "聚光燈",
    "spread cleavage": "撥開乳溝",
    "spread legs": "張開雙腿",
    "spread pussy": "張開陰部",
    "squatting": "蹲著",
    "standing": "站著",
    "standing doggystyle": "站立後入",
    "standing on one leg": "單腳站",
    "standing sex": "站立性交",
    "starry sky": "星空",
    "steam": "蒸氣",
    "steaming body": "身體冒熱氣",
    "straddling": "跨坐",
    "straight hair": "直髮",
    "strap slip": "肩帶滑落",
    "streaked hair": "條紋挑染",
    "street": "街道",
    "string bikini": "細繩比基尼",
    "stubble": "鬍渣",
    "suit": "套裝",
    "sundress": "太陽裙",
    "sunlight": "陽光",
    "sunrise": "日出",
    "sunset": "日落",
    "suspended congress": "懸空體位",
    "sweat": "汗",
    "sweater": "毛衣",
    "sweater dress": "針織洋裝",
    "swept bangs": "側撥瀏海",
    "swim briefs": "三角泳褲",
    "swimsuit": "泳裝",
    "t-shirt": "T恤",
    "tall female": "高個女性",
    "tan": "曬黑",
    "tangzhuang": "唐裝",
    "tank top": "背心",
    "tanlines": "曬痕",
    "tareme": "垂眼",
    "tatami": "榻榻米",
    "tattoo": "刺青",
    "temple": "神殿／寺廟",
    "testicles": "睪丸",
    "thick eyebrows": "濃眉",
    "thick thighs": "粗腿",
    "thighhighs": "過膝襪",
    "thong": "丁字褲",
    "throne": "王座",
    "tight clothes": "緊身衣",
    "toga": "托加",
    "toned": "結實身材",
    "toned male": "結實男性",
    "tongue out": "吐舌",
    "top hat": "高禮帽",
    "top-down bottom-up": "上身下俯下身仰視",
    "topless female": "女性露胸",
    "topless male": "男性赤膊",
    "torii": "鳥居",
    "train": "列車",
    "train interior": "車廂內部",
    "tribadism": "磨鏡",
    "tsurime": "吊眼",
    "tuxedo": "燕尾服",
    "twin braids": "雙辮",
    "twintails": "雙馬尾",
    "two-tone hair": "雙色髮",
    "unbuttoned shirt": "解開鈕扣的襯衫",
    "underwater": "水下",
    "underwear only": "只穿內衣",
    "undressing": "正在脫衣",
    "upper body": "上半身",
    "upskirt": "裙底視角",
    "v": "比V",
    "vaginal": "陰道插入",
    "veiny penis": "青筋陰莖",
    "very aesthetic": "非常有美感",
    "very dark skin": "非常深的膚色",
    "very long hair": "非常長的頭髮",
    "very short hair": "極短髮",
    "victorian": "維多利亞風格",
    "violet eyes": "紫羅藍眼",
    "waistcoat": "背心馬甲",
    "wariza": "割坐",
    "wavy hair": "波浪髮",
    "wedding dress": "婚紗",
    "wedgie": "內褲勒入",
    "wet": "濕",
    "wet clothes": "濕衣",
    "white hair": "白髮",
    "wide hips": "寬臀",
    "wide sleeves": "寬袖",
    "window": "窗戶",
    "window light": "窗光",
    "wink": "眨眼",
    "yellow eyes": "黃眼",
    "yoga pants": "瑜珈褲",
    "yukata": "浴衣",
    "breasts": "胸部",
    "hetero": "異性",
    "male pubic hair": "男性陰毛",
    "female pubic hair": "女性陰毛",
    "thighs": "大腿",
    "girl on top": "女上",
    "tongue": "舌頭",
    "bare shoulders": "露肩",
    "breasts out": "胸部露出",
    "on bed": "在床上",
    "ass": "臀部",
    "sky": "天空",
    "teeth": "牙齒",
    "closed mouth": "閉嘴",
    "pillow": "枕頭",
    "white shirt": "白襯衫",
    "single hair bun": "單髮髻",
    "water": "水",
    "long sleeves": "長袖",
    "oral": "口交",
    "parted bangs": "分瀏海",
    "saliva": "唾液",
    "curtains": "窗簾",
    "pregnant": "懷孕",
    "office lady": "OL",
    "sex toy": "性玩具",
    "vibrator": "震動棒",
    "wedding ring": "婚戒",
    "ring": "戒指",
    "clothed male nude female": "男著衣女裸",
    "clothed female nude male": "女著衣男裸",
    "group sex": "群交",
    "threesome": "3P",
    "high-waist skirt": "高腰裙",
    "sports bra": "運動內衣",
    "collared shirt": "有領襯衫",
    "closed eyes": "閉眼",
    "tears": "眼淚",
    "tree": "樹",
    "candle": "蠟燭",
    "bed sheet": "床單",
    "blue sky": "藍天",
    "car": "車",
    "underwear": "內衣",
    "kiss": "接吻",
    "holding hands": "牽手",
    "shoes": "鞋子",
    "coat": "外套",
    "belt": "腰帶",
    "bag": "包",
    "ass ripple": "臀波",
    "pink nails": "粉指甲",
    "clitoris": "陰蒂",
    "yuri": "百合",
    "on chair": "坐椅子上",
    "office chair": "辦公椅",
    "wet shirt": "濕襯衫",
    "black skirt": "黑裙",
    "white dress": "白洋裝",
    "police uniform": "警察制服",
    "mixed-sex bathing": "男女混浴",
    "pov crotch": "胯下第一人稱",
    "looking at mirror": "看鏡子",
    "implied sex": "暗示性愛",
    "stealth sex": "隱密做愛",
    "after fellatio": "口交事後",
    "after paizuri": "乳交事後",
    "mmf threesome": "兩男一女",
    "ffm threesome": "兩女一男",
    "leg lift": "抬腿",
    "city lights": "城市燈光",
    "restaurant": "餐廳",
    "bamboo forest": "竹林",
    "beach towel": "海灘巾",
    "pool ladder": "泳池扶梯",
    "park bench": "公園長椅",
    "ceiling light": "吸頂燈",
    "carpet": "地毯",
    "orange sky": "橘空",
    "cum pool": "精液灘",
    "bush": "灌木",
    "tooth necklace": "牙項鍊",
    "open coat": "敞開外套",
    "dress pull": "拉洋裝",
    "short sleeves": "短袖",
    "blue shirt": "藍襯衫",
    "black shirt": "黑襯衫",
    "green shirt": "綠襯衫",
    "blue pants": "藍褲",
    "black pants": "黑褲",
    "blue skirt": "藍裙",
    "blue dress": "藍洋裝",
    "red dress": "紅洋裝",
    "green dress": "綠洋裝",
    "blue jacket": "藍外套",
    "black jacket": "黑外套",
    "shirt tucked in": "下擺紮進",
    "collared shirt": "有領襯衫",
    "competition swimsuit": "競技泳裝",
    "blue one-piece swimsuit": "藍連身泳裝",
    "one-piece swimsuit pull": "拉連身泳裝",
    "stud earrings": "耳釘",
    "hoop earrings": "圈耳環",
    "black collar": "黑項圈",
    "egg vibrator": "跳蛋",
    "grabbing another's breast": "抓別人的胸",
    "grabbing own breast": "抓自己的胸",
    "breasts squeezed together": "胸部擠在一起",
    "bouncing breasts": "胸部晃動",
    "breast lift": "托胸",
    "breast press": "壓胸",
    "breast rest": "墊胸",
    "breasts on table": "胸部放桌上",
    "mole on breast": "胸上痣",
    "covered navel": "遮肚臍",
    "covered nipples": "遮乳頭",
    "inverted nipples": "凹陷乳頭",
    "huge nipples": "巨大乳頭",
    "nipple stimulation": "刺激乳頭",
    "large areolae": "大乳暈",
    "multicolored hair": "多色髮",
    "wet hair": "濕髮",
    "hair scrunchie": "髮圈",
    "hair flower": "髮花",
    "parted bangs": "分瀏海",
    "single hair bun": "單髮髻",
    "licking penis": "舔陰莖",
    "penis out": "陰莖露出",
    "looking at penis": "看著陰莖",
    "thigh gap": "腿縫",
    "imminent fellatio": "即將口交",
    "perpendicular paizuri": "垂直乳交",
    "holding sex toy": "拿著性玩具",
    "lifting person": "抱起人",
    "sports bra lift": "掀運動內衣",
    "sweater lift": "掀毛衣",
    "vaginal object insertion": "陰道塞物",
    "squatting cowgirl position": "蹲姿騎乘",
    "shared bathing": "共浴",
    "clothed sex": "著衣做愛",
    "poolside": "泳池邊",

    "dudou": "肚兜",
    "sash": "腰帶",
    "hair stick": "髮簪",
    "hairpin": "髮釵",
    "pelvic curtain": "遮胯巾",
    "chiton": "希頓袍",
    "peplos": "佩普洛斯",
    "himation": "希馬提翁",
    "tunic": "束腰外衣",
    "cloak": "披風",
    "hood": "兜帽",
    "circlet": "頭環",
    "leather armor": "皮甲",
    "haori": "羽織",
    "kanzashi": "花簪",
    "zouri": "草履",
    "bonnet": "軟帽",
    "parasol": "陽傘",
    "cravat": "領巾",
    "courtyard": "庭院",
    "pavilion": "亭臺",
    "lotus pond": "荷塘",
    "colonnade": "柱廊",
    "great hall": "大廳",
    "chair": "椅子",
    "swivel chair": "旋轉椅",
    "gaming chair": "電競椅",
    "blue sports bra": "藍運動內衣",
    "bra visible through clothes": "衣服透出胸罩",
    "sleeves rolled up": "袖子捲起",
    "black bra": "黑胸罩",
    "side-tie bikini bottom": "側綁比基尼下身",
    "blue necktie": "藍領帶",
    "black dress": "黑洋裝",
    "white sweater": "白毛衣",
    "white kimono": "白和服",
    "white tank top": "白背心",
    "umbrella": "雨傘",
    "green sweater": "綠毛衣",
    "blue bodysuit": "藍緊身衣",
    "black belt": "黑腰帶",
    "green jacket": "綠外套",
    "white coat": "白大衣",
    "detached collar": "分離領",
    "black panties": "黑內褲",
    "hard hat": "安全帽",
    "black bodysuit": "黑緊身衣",
    "nun": "修女服",
    "sleeveless shirt": "無袖襯衫",
    "black shorts": "黑短褲",
    "black thighhighs": "黑過膝襪",
    "detached sleeves": "分離袖",
    "brown belt": "棕腰帶",
    "pink shirt": "粉襯衫",
    "blue sweater": "藍毛衣",
    "animal collar": "寵物項圈",
    "bead necklace": "珠項鍊",
    "watch": "手錶",
    "blue bikini": "藍比基尼",
    "purple dress": "紫洋裝",
    "shoulder armor": "肩甲",
    "cardigan": "開襟衫",
    "white bra": "白胸罩",
    "blue bra": "藍胸罩",
    "brown pants": "棕褲",
    "off-shoulder sweater": "露肩毛衣",
    "open bodysuit": "敞開緊身衣",
    "black gloves": "黑手套",
    "blue kimono": "藍和服",
    "pink bikini": "粉比基尼",
    "military uniform": "軍服",
    "red bodysuit": "紅緊身衣",
    "high-waist pants": "高腰褲",
    "turtleneck sweater": "高領毛衣",
    "brown skirt": "棕裙",
    "police hat": "警帽",
    "sleeveless dress": "無袖洋裝",
    "bath yukata": "浴浴衣",
    "red shirt": "紅襯衫",
    "brown coat": "棕大衣",
    "cross necklace": "十字架項鍊",
    "dress shirt": "禮服襯衫",
    "ribbed sweater": "羅紋毛衣",
    "track uniform": "運動服",
    "see-through shirt": "透明襯衫",
    "white panties": "白內褲",
    "red one-piece swimsuit": "紅連身泳裝",
    "open cardigan": "敞開開襟衫",
    "red panties": "紅內褲",
    "naked coat": "只穿大衣",
    "track jacket": "運動外套",
    "naked jacket": "只穿外套",
    "red collar": "紅項圈",
    "black sports bra": "黑運動內衣",
    "aqua shirt": "水色襯衫",
    "puffy sleeves": "泡泡袖",
    "blue shorts": "藍短褲",
    "pink dress": "粉洋裝",
    "tassel earrings": "流蘇耳環",
    "basketball uniform": "籃球服",
    "white socks": "白襪",
    "purple kimono": "紫和服",
    "red sweater": "紅毛衣",
    "vest": "馬甲",
    "pink sports bra": "粉運動內衣",
    "pink bra": "粉胸罩",
    "black bowtie": "黑領結",
    "power armor": "動力裝甲",
    "beach umbrella": "海灘傘",
    "white skirt": "白裙",
    "black tank top": "黑背心",
    "torn bodysuit": "破緊身衣",
    "casual one-piece swimsuit": "休閒連身泳裝",
    "black necktie": "黑領帶",
    "blue panties": "藍內褲",
    "black leotard": "黑連身衣",
    "white one-piece swimsuit": "白連身泳裝",
    "handbag": "手提包",
    "long skirt": "長裙",
    "o-ring": "O環",
    "off-shoulder dress": "露肩洋裝",
    "red tank top": "紅背心",
    "swimsuit aside": "撥開泳裝",
    "shirt pull": "拉襯衫",
    "sweater pull": "拉毛衣",
    "bikini bottom aside": "撥開比基尼下身",
    "leotard aside": "撥開連身衣",
    "breasts on glass": "胸部貼玻璃",
    "breasts apart": "胸部分開",
    "condom on penis": "套著保險套",
    "arm hair": "手臂毛",
    "leg hair": "腿毛",
    "tweaking own nipple": "搓自己乳頭",
    "arm under breasts": "手臂托胸",
    "cum on ass": "精液在臀上",
    "grabbing another's hair": "抓別人頭髮",
    "nipple piercing": "乳頭環",
    "arms under breasts": "雙臂托胸",
    "glowing eyes": "發光眼",
    "guided breast grab": "引導抓胸",
    "breast bondage": "胸部束縛",
    "grabbing another's ass": "抓別人的臀",
    "unaligned breasts": "左右胸不齊",
    "parted hair": "中分髮",
    "thigh strap": "大腿綁帶",
    "penis on ass": "陰莖放臀上",
    "breast suppress": "壓胸",
    "goblin": "哥布林",
    "orc": "獸人",
    "hobgoblin": "霍布哥布林",
    "oni": "鬼",
    "ogre": "食人魔",
    "troll": "巨魔",
    "kobold": "狗頭人",
    "lizardman": "蜥蜴人",
    "minotaur": "牛頭人",
    "centaur": "半人馬",
    "satyr": "羊人",
    "incubus": "男夢魔",
    "demon": "惡魔",
    "werewolf": "狼人",
    "naga": "蛇人",
    "slime boy": "史萊姆男",
    "zombie": "殭屍",
    "skeleton": "骷髏",
    "alien": "外星人",
    "elf": "精靈",
    "dark elf": "黑暗精靈",
    "dwarf": "矮人",
    "vampire": "吸血鬼",
    "merman": "人魚男",
    "wolf boy": "狼男",
    "cat boy": "貓男",
    "dog boy": "狗男",
    "fox boy": "狐男",
    "rabbit boy": "兔男",
    "horse boy": "馬男",
    "bear boy": "熊男",
    "tiger boy": "虎男",
    "lion boy": "獅男",
    "dragon boy": "龍男",
    "shark boy": "鯊魚男",
    "tanuki": "狸男",
    "monster boy": "怪物男",
    "ugly bastard": "醜男",
    "fat": "肥胖",
    "fat man": "胖男",
    "obese": "過胖",
    "manboobs": "男性胸部",
    "old man": "老年男性",
    "bald": "禿頭",
    "otaku": "宅男",
    "nerd": "書呆",
    "coke-bottle glasses": "瓶底眼鏡",
}


COLORS = {
    "white": "白",
    "black": "黑",
    "blue": "藍",
    "green": "綠",
    "red": "紅",
    "pink": "粉",
    "purple": "紫",
    "brown": "棕",
    "aqua": "水色",
    "orange": "橘",
    "yellow": "黃",
    "grey": "灰",
    "gray": "灰",
}

ITEMS = {
    "shirt": "襯衫",
    "dress": "洋裝",
    "skirt": "裙子",
    "pants": "褲子",
    "shorts": "短褲",
    "sweater": "毛衣",
    "jacket": "外套",
    "coat": "大衣",
    "bra": "胸罩",
    "panties": "內褲",
    "bikini": "比基尼",
    "necktie": "領帶",
    "bowtie": "領結",
    "kimono": "和服",
    "bodysuit": "緊身衣",
    "leotard": "連身衣",
    "socks": "襪子",
    "gloves": "手套",
    "collar": "項圈",
    "hat": "帽子",
    "tank top": "背心",
    "sports bra": "運動內衣",
    "one-piece swimsuit": "連身泳裝",
    "cardigan": "開襟衫",
}


def auto_zh(tag: str) -> str | None:
    if tag in ZH:
        return ZH[tag]
    for color, czh in COLORS.items():
        prefix = color + " "
        if tag.startswith(prefix):
            rest = tag[len(prefix) :]
            if rest in ZH:
                return czh + ZH[rest]
            if rest in ITEMS:
                return czh + ITEMS[rest]
    return None


def main() -> None:
    data = json.loads(LEX.read_text(encoding="utf-8"))
    missing = []
    for item in data["tags"]:
        zh = auto_zh(item["tag"])
        if not zh:
            missing.append(item["tag"])
            zh = item["tag"]
        item["zh"] = zh
    data["zh"] = {
        t: ZH[t]
        for t in list(data["quality"]) + list(data["nsfwTail"]) + list(data["alwaysEnv"])
        if t in ZH
    }
    LEX.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"zh attached, missing {len(missing)}")
    for t in missing:
        print(" MISSING", t)


if __name__ == "__main__":
    main()
