"""Rebuild/check the WEB6 Chiron subset without making vocabulary edits depend on a build.

python scripts/build_web6_fonts.py --check              # stdlib only; no network
python scripts/build_web6_fonts.py --build --download    # requires fonts-requirements.txt
python scripts/build_web6_fonts.py --verify --source /path/to/pinned-source.ttf
python scripts/build_web6_fonts.py --build-serif --download   # the films' Noto Serif TC 900 titles
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
from pathlib import Path
import re
import sys
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "web6/fonts"
META = ASSETS / "chiron-source.json"
MANIFEST = ASSETS / "chiron-subset.json"
FONT = ASSETS / "chiron-hei-hk-web6.woff2"
CSS = ROOT / "web6/fonts.css"
# 介紹影片、教學的超大標題是明體（Noto Serif TC 900）。只收影片和教學原始檔裡出現的字，
# 只有用到這個字族的元素才會下載它（一般房間不會）。來源釘在 google/fonts 的一個 commit。
SERIF = ASSETS / "noto-serif-tc-film.woff2"
SERIF_MANIFEST = ASSETS / "noto-serif-subset.json"
SERIF_SOURCE = {
    "url": "https://raw.githubusercontent.com/google/fonts/8b0a1d0f5983c89bc2b93f1b5fb55f9e252744b5/ofl/notoseriftc/NotoSerifTC%5Bwght%5D.ttf",
    "sha256": "0077e18f57c6908f4a000969880940bdb0dad057c0e8d98b49dc364c3d1b09c6",
    "path": ROOT / ".planning/font-investigation/NotoSerifTC-wght.ttf",
}
SERIF_WEIGHT = 900


def digest(data):
    return hashlib.sha256(data).hexdigest()


def ranges(points):
    result = []
    for point in sorted(points):
        if result and point == result[-1][1] + 1:
            result[-1][1] = point
        else:
            result.append([point, point])
    return ", ".join(f"U+{a:X}" + (f"-{b:X}" if b != a else "") for a, b in result)


def points(value):
    result = set()
    for token in value.split(","):
        pair = token.strip().removeprefix("U+").split("-")
        low = int(pair[0], 16)
        high = int(pair[-1].replace("?", "F"), 16)
        result.update(range(low, high + 1))
    return result


def corpus():
    # Include source comments as a conservative superset of display strings. Resolve
    # the same WEB6 -> web module fallback as server.py, including future imports.
    files = set(p for p in (ROOT / "web6").iterdir() if p.suffix in {".html", ".js", ".css"} and p != CSS)
    queue = list(files)
    while queue:
        path = queue.pop()
        text = path.read_text(encoding="utf-8")
        for relative in re.findall(r"(?:from\s*|import\s*\(?|@import\s*)(?:[\"'])(\.[^\"']+)[\"']", text):
            candidate = (path.parent / relative).resolve()
            if not candidate.is_file() and candidate.is_relative_to(ROOT / "web6"):
                candidate = ROOT / "web" / candidate.relative_to(ROOT / "web6")
            if candidate.is_file() and candidate not in files:
                files.add(candidate)
                queue.append(candidate)
    files.add(ROOT / "web/lexicon.json")
    characters = set(chr(c) for c in range(0x20, 0x7f))
    for path in files:
        text = html.unescape(path.read_text(encoding="utf-8"))
        text = re.sub(r"\\u\{([0-9a-fA-F]+)\}|\\u([0-9a-fA-F]{4})", lambda m: chr(int(m[1] or m[2], 16)), text)
        characters.update(c for c in text if c.isprintable())
    return {ord(c) for c in characters}, sorted(str(p.relative_to(ROOT)).replace("\\", "/") for p in files)


# IBM Plex Mono（種子、張數）：IBM 官方發布、沒改過的完整檔（OFL，保留字型名稱 "Plex"，所以不能自己裁）。
PLEX = [("IBMPlexMono-Regular.woff2", "400"), ("IBMPlexMono-Medium.woff2", "500 700")]


def css_text(unicodes, metadata):
    lines = ["/* Generated by scripts/build_web6_fonts.py. Chiron Hei HK 2.530 and IBM Plex Mono 1.1.0, SIL OFL 1.1.",
             " * Everything is local: no Google Fonts requests. Characters outside the Chiron subset",
             " * (new vocabulary, user text) use the system fallback until the subset is rebuilt. */"]
    # The subset keeps the source's full wght axis (200-900), so body text and headings share one file.
    font_version = digest(FONT.read_bytes())[:10]
    lines.extend(["@font-face {", '  font-family: "Chiron Hei HK";', "  font-style: normal;",
                  "  font-weight: 200 900;", "  font-display: swap;",
                  f'  src: url("fonts/chiron-hei-hk-web6.woff2?v={font_version}") format("woff2");',
                  f"  unicode-range: {ranges(unicodes)};", "}"])
    if SERIF_MANIFEST.is_file():
        serif = json.loads(SERIF_MANIFEST.read_text(encoding="utf-8"))
        lines.extend(["@font-face {", '  font-family: "Noto Serif TC";', "  font-style: normal;",
                      f"  font-weight: {SERIF_WEIGHT};", "  font-display: swap;",
                      f'  src: url("fonts/{SERIF.name}?v={serif["sha256"][:10]}") format("woff2");',
                      f'  unicode-range: {ranges(serif["unicodes"])};', "}"])
    for name, weight in PLEX:
        lines.extend(["@font-face {", '  font-family: "IBM Plex Mono";', "  font-style: normal;",
                      f"  font-weight: {weight};", "  font-display: swap;",
                      f'  src: url("fonts/{name}?v={digest((FONT.parent / name).read_bytes())[:10]}") format("woff2");', "}"])
    return "\n".join(lines) + "\n"


def film_corpus():
    """影片、教學的原始檔（含註解，寬一點沒關係）裡的字。"""
    names = re.compile(r"^(film|tut|tutorial|intro)")
    files = sorted(p for p in (ROOT / "web6").iterdir() if names.match(p.name) and p.suffix in {".html", ".js", ".css"})
    characters = set(chr(c) for c in range(0x20, 0x7f))
    for path in files:
        characters.update(c for c in html.unescape(path.read_text(encoding="utf-8")) if c.isprintable())
    return {ord(c) for c in characters}


def build_serif(args):
    from fontTools import subset
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont
    path = Path(args.source) if args.source else SERIF_SOURCE["path"]
    if args.download:
        path.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(SERIF_SOURCE["url"]) as response:
            path.write_bytes(response.read())
    if not path.is_file():
        raise SystemExit("Provide --source NotoSerifTC[wght].ttf or --download.")
    assert digest(path.read_bytes()) == SERIF_SOURCE["sha256"], "Serif source checksum mismatch"
    font = instantiateVariableFont(TTFont(path, recalcTimestamp=False), {"wght": SERIF_WEIGHT}, inplace=False)
    included = film_corpus() & set(font.getBestCmap())
    options = subset.Options()
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.notdef_outline = True
    options.recalc_timestamp = False
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=included)
    worker.subset(font)
    font.flavor = "woff2"
    font.save(SERIF, reorderTables=True)
    manifest = {"sha256": digest(SERIF.read_bytes()), "bytes": SERIF.stat().st_size, "source": SERIF_SOURCE["url"],
                "source_sha256": SERIF_SOURCE["sha256"], "weight": SERIF_WEIGHT, "unicodes": sorted(included)}
    SERIF_MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Film serif: {manifest['bytes']:,} bytes, {len(included):,} codepoints.")


def check(metadata):
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    included = set(manifest["unicodes"])
    current, _ = corpus()
    fallback = set().union(*(points(f["unicode_range"]) for f in metadata["fallback_faces"]))
    assert digest(FONT.read_bytes()) == manifest["sha256"], "Subset changed; rebuild it"
    assert CSS.read_text(encoding="utf-8") == css_text(included, metadata), "Font CSS changed; rebuild it"
    if SERIF_MANIFEST.is_file():
        serif = json.loads(SERIF_MANIFEST.read_text(encoding="utf-8"))
        assert digest(SERIF.read_bytes()) == serif["sha256"], "Film serif changed; rebuild it"
        missing = film_corpus() - set(serif["unicodes"]) - set(range(0x20, 0x7f))
        if missing:
            print(f"{len(missing)} film characters are not in the serif subset (they draw in Chiron); --build-serif adds any Noto Serif TC has.")
    new = (current & fallback) - included
    print(f"Subset: {FONT.stat().st_size:,} bytes, {len(included):,} codepoints; current corpus {len(current):,}.")
    if new:
        print(f"{len(new)} characters are outside the local subset and use the system font; a rebuild adds any the source font has: {ranges(new)}")
    else:
        print("All current source characters supported by Chiron use the local subset.")
    original_missing = current - included - fallback
    print(f"{len(original_missing)} characters are not in Chiron Hei HK at all; the system fallback chain draws them.")
    return included


def original(args, metadata):
    path = Path(args.source) if args.source else ROOT / ".planning/font-investigation/ChironHeiHK-variable.ttf"
    if args.download:
        path.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(metadata["source_url"]) as response:
            path.write_bytes(response.read())
    if not path.is_file():
        raise SystemExit("Provide --source FONT.ttf or --download; no font download is required for --check.")
    assert digest(path.read_bytes()) == metadata["source_sha256"], "Source checksum mismatch"
    return path


def build(args, metadata):
    from fontTools import subset
    from fontTools.ttLib import TTFont
    path = original(args, metadata)
    font = TTFont(path, recalcTimestamp=False)
    current, files = corpus()
    included = current & set(font.getBestCmap())
    options = subset.Options()
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.name_legacy = True
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recalc_timestamp = False
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=included)
    worker.subset(font)
    font.flavor = "woff2"
    font.save(FONT, reorderTables=True)
    manifest = {"sha256": digest(FONT.read_bytes()), "bytes": FONT.stat().st_size,
                "source_sha256": metadata["source_sha256"], "unicodes": sorted(included),
                "corpus_files": files, "axes": [{"tag": a.axisTag, "min": a.minValue, "default": a.defaultValue, "max": a.maxValue} for a in font["fvar"].axes],
                "fonttools": "4.61.1", "brotli": "1.2.0"}
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    CSS.write_text(css_text(included, metadata), encoding="utf-8", newline="\n")
    check(metadata)


def verify(args, metadata):
    from fontTools.ttLib import TTFont
    from fontTools.pens.recordingPen import DecomposingRecordingPen
    from fontTools.varLib.instancer import instantiateVariableFont
    source = TTFont(original(args, metadata), recalcTimestamp=False)
    local = TTFont(FONT, recalcTimestamp=False)
    included = check(metadata)
    axis = lambda f: [(a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in f["fvar"].axes]
    assert axis(source) == axis(local), "Variable axis differs"
    for tag, attributes in {"head": ["unitsPerEm"], "hhea": ["ascent", "descent", "lineGap"],
                            "vhea": ["ascent", "descent", "lineGap"], "OS/2": ["sTypoAscender", "sTypoDescender", "sTypoLineGap", "usWinAscent", "usWinDescent"]}.items():
        for attr in attributes:
            assert getattr(source[tag], attr) == getattr(local[tag], attr), (tag, attr)
    for weight in (700, 800):
        large = instantiateVariableFont(source, {"wght": weight}, inplace=False)
        small = instantiateVariableFont(local, {"wght": weight}, inplace=False)
        big_glyphs, small_glyphs = large.getGlyphSet(), small.getGlyphSet()
        for code in included:
            big_name, small_name = large.getBestCmap()[code], small.getBestCmap()[code]
            for tag in ("hmtx", "vmtx"):
                assert large[tag][big_name] == small[tag][small_name], (weight, code, tag)
            big_pen, small_pen = DecomposingRecordingPen(big_glyphs), DecomposingRecordingPen(small_glyphs)
            big_glyphs[big_name].draw(big_pen)
            small_glyphs[small_name].draw(small_pen)
            assert big_pen.value == small_pen.value, (weight, f"U+{code:X}", "outline")
        print(f"Weight {weight}: {len(included):,} glyph outlines and horizontal/vertical metrics exactly match source.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--build", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--build-serif", action="store_true")
    parser.add_argument("--download", action="store_true")
    parser.add_argument("--source")
    args = parser.parse_args()
    metadata = json.loads(META.read_text(encoding="utf-8"))
    if args.build_serif:
        build_serif(args)
        CSS.write_text(css_text(set(json.loads(MANIFEST.read_text(encoding="utf-8"))["unicodes"]), metadata), encoding="utf-8", newline="\n")
    if args.build:
        build(args, metadata)
    if args.verify:
        verify(args, metadata)
    if args.check or not (args.build or args.verify or args.build_serif):
        check(metadata)


if __name__ == "__main__":
    main()
