"""Rebuild/check the WEB6 Chiron subset without making vocabulary edits depend on a build.

python scripts/build_web6_fonts.py --check              # stdlib only; no network
python scripts/build_web6_fonts.py --build --download    # requires fonts-requirements.txt
python scripts/build_web6_fonts.py --verify --source /path/to/pinned-source.ttf
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
from pathlib import Path
import re
import sys
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "web6/fonts"
META = ASSETS / "chiron-source.json"
MANIFEST = ASSETS / "chiron-subset.json"
FONT = ASSETS / "chiron-hei-hk-web6.woff2"
CSS = ROOT / "web6/fonts.css"


def digest(data):
    return hashlib.sha256(data).hexdigest()


def ranges(points):
    result = []
    for point in sorted(points):
        if result and point == result[-1][1] + 1:
            result[-1][1] = point
        else:
            result.append([point, point])
    return ", ".join(f"U+{a:X}" + (f"-{b:X}" if b != a else "") for a, b in result)


def points(value):
    result = set()
    for token in value.split(","):
        pair = token.strip().removeprefix("U+").split("-")
        low = int(pair[0], 16)
        high = int(pair[-1].replace("?", "F"), 16)
        result.update(range(low, high + 1))
    return result


def corpus():
    # Include source comments as a conservative superset of display strings. Resolve
    # the same WEB6 -> web module fallback as server.py, including future imports.
    files = set(p for p in (ROOT / "web6").iterdir() if p.suffix in {".html", ".js", ".css"} and p != CSS)
    queue = list(files)
    while queue:
        path = queue.pop()
        text = path.read_text(encoding="utf-8")
        for relative in re.findall(r"(?:from\s*|import\s*\(?|@import\s*)(?:[\"'])(\.[^\"']+)[\"']", text):
            candidate = (path.parent / relative).resolve()
            if not candidate.is_file() and candidate.is_relative_to(ROOT / "web6"):
                candidate = ROOT / "web" / candidate.relative_to(ROOT / "web6")
            if candidate.is_file() and candidate not in files:
                files.add(candidate)
                queue.append(candidate)
    files.add(ROOT / "web/lexicon.json")
    characters = set(chr(c) for c in range(0x20, 0x7f))
    for path in files:
        text = html.unescape(path.read_text(encoding="utf-8"))
        text = re.sub(r"\\u\{([0-9a-fA-F]+)\}|\\u([0-9a-fA-F]{4})", lambda m: chr(int(m[1] or m[2], 16)), text)
        characters.update(c for c in text if c.isprintable())
    return {ord(c) for c in characters}, sorted(str(p.relative_to(ROOT)).replace("\\", "/") for p in files)


def css_text(unicodes, metadata):
    lines = ["/* Generated by scripts/build_web6_fonts.py. Chiron Hei HK 2.530, SIL OFL 1.1.",
             " * The local face covers WEB6 source/labels. Disjoint upstream faces handle new text.",
             " * Never preload the complementary faces: their unicode-range loads them on demand. */"]
    # Composite unicode faces need identical style/weight descriptors. Keep the
    # original requested 700/800 range while retaining the source's full axis data.
    font_version = digest(FONT.read_bytes())[:10]
    faces = [{"url": f"fonts/chiron-hei-hk-web6.woff2?v={font_version}", "weight": "700 800", "unicode_range": ranges(unicodes)}]
    for face in metadata["fallback_faces"]:
        remaining = points(face["unicode_range"]) - unicodes
        if remaining:
            faces.append({**face, "unicode_range": ranges(remaining)})
    for face in faces:
        lines.extend(["@font-face {", '  font-family: "Chiron Hei HK";', "  font-style: normal;",
                      f'  font-weight: {face["weight"]};', "  font-display: swap;",
                      f'  src: url("{face["url"]}") format("woff2");',
                      f'  unicode-range: {face["unicode_range"]};', "}"])
    return "\n".join(lines) + "\n"


def check(metadata):
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    included = set(manifest["unicodes"])
    current, _ = corpus()
    fallback = set().union(*(points(f["unicode_range"]) for f in metadata["fallback_faces"]))
    assert digest(FONT.read_bytes()) == manifest["sha256"], "Subset changed; rebuild it"
    assert CSS.read_text(encoding="utf-8") == css_text(included, metadata), "Font CSS changed; rebuild it"
    new = (current & fallback) - included
    print(f"Subset: {FONT.stat().st_size:,} bytes, {len(included):,} codepoints; current corpus {len(current):,}.")
    if new:
        print(f"{len(new)} newly introduced characters use matching upstream faces; optional rebuild: {ranges(new)}")
    else:
        print("All current source characters supported by Chiron use the local subset.")
    original_missing = current - included - fallback
    print(f"{len(original_missing)} characters fall outside the original Google web faces; existing system/body fallbacks still apply.")
    return included


def original(args, metadata):
    path = Path(args.source) if args.source else ROOT / ".planning/font-investigation/ChironHeiHK-variable.ttf"
    if args.download:
        path.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(metadata["source_url"]) as response:
            path.write_bytes(response.read())
    if not path.is_file():
        raise SystemExit("Provide --source FONT.ttf or --download; no font download is required for --check.")
    assert digest(path.read_bytes()) == metadata["source_sha256"], "Source checksum mismatch"
    return path


def build(args, metadata):
    from fontTools import subset
    from fontTools.ttLib import TTFont
    path = original(args, metadata)
    font = TTFont(path, recalcTimestamp=False)
    current, files = corpus()
    included = current & set(font.getBestCmap())
    options = subset.Options()
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.name_legacy = True
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recalc_timestamp = False
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=included)
    worker.subset(font)
    font.flavor = "woff2"
    font.save(FONT, reorderTables=True)
    manifest = {"sha256": digest(FONT.read_bytes()), "bytes": FONT.stat().st_size,
                "source_sha256": metadata["source_sha256"], "unicodes": sorted(included),
                "corpus_files": files, "axes": [{"tag": a.axisTag, "min": a.minValue, "default": a.defaultValue, "max": a.maxValue} for a in font["fvar"].axes],
                "fonttools": "4.61.1", "brotli": "1.2.0"}
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    CSS.write_text(css_text(included, metadata), encoding="utf-8", newline="\n")
    check(metadata)


def verify(args, metadata):
    from fontTools.ttLib import TTFont
    from fontTools.pens.recordingPen import DecomposingRecordingPen
    from fontTools.varLib.instancer import instantiateVariableFont
    source = TTFont(original(args, metadata), recalcTimestamp=False)
    local = TTFont(FONT, recalcTimestamp=False)
    included = check(metadata)
    axis = lambda f: [(a.axisTag, a.minValue, a.defaultValue, a.maxValue) for a in f["fvar"].axes]
    assert axis(source) == axis(local), "Variable axis differs"
    for tag, attributes in {"head": ["unitsPerEm"], "hhea": ["ascent", "descent", "lineGap"],
                            "vhea": ["ascent", "descent", "lineGap"], "OS/2": ["sTypoAscender", "sTypoDescender", "sTypoLineGap", "usWinAscent", "usWinDescent"]}.items():
        for attr in attributes:
            assert getattr(source[tag], attr) == getattr(local[tag], attr), (tag, attr)
    for weight in (700, 800):
        large = instantiateVariableFont(source, {"wght": weight}, inplace=False)
        small = instantiateVariableFont(local, {"wght": weight}, inplace=False)
        big_glyphs, small_glyphs = large.getGlyphSet(), small.getGlyphSet()
        for code in included:
            big_name, small_name = large.getBestCmap()[code], small.getBestCmap()[code]
            for tag in ("hmtx", "vmtx"):
                assert large[tag][big_name] == small[tag][small_name], (weight, code, tag)
            big_pen, small_pen = DecomposingRecordingPen(big_glyphs), DecomposingRecordingPen(small_glyphs)
            big_glyphs[big_name].draw(big_pen)
            small_glyphs[small_name].draw(small_pen)
            assert big_pen.value == small_pen.value, (weight, f"U+{code:X}", "outline")
        print(f"Weight {weight}: {len(included):,} glyph outlines and horizontal/vertical metrics exactly match source.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--build", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument("--download", action="store_true")
    parser.add_argument("--source")
    args = parser.parse_args()
    metadata = json.loads(META.read_text(encoding="utf-8"))
    if args.build:
        build(args, metadata)
    if args.verify:
        verify(args, metadata)
    if args.check or not (args.build or args.verify):
        check(metadata)


if __name__ == "__main__":
    main()
