import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {test} from 'node:test';
const src = f => readFileSync(new URL('../'+f, import.meta.url), 'utf8');
const moduleOf = async (file, prelude='') => import('data:text/javascript;base64,'+Buffer.from(prelude+src(file).replace(/^import .*?;\r?\n/gm,'')).toString('base64'));
const {createGenerator} = await moduleOf('web6/gen.js', 'const escapeForComfy = s => s;\n');
const memory = new Map();
globalThis.localStorage = {getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};
const store = await import('../web6/store.js');
const {sanitizeSettings} = await import('../web/engine.js');
const {toggleHeat,weightsForHeats} = await import('../web/heats.js');
const data = JSON.parse(src('web/lexicon.json'));
const fnSource = (file,name) => { const s=src(file);const start=s.indexOf('function '+name+'('); const end=s.indexOf('\n}',start);return s.slice(start,end+2); };
const evaluate = (file,name,ctx) => {vm.createContext(ctx);return vm.runInContext(fnSource(file,name)+'\n'+name,ctx);};
const payload = file => {const s=src(file);return vm.runInNewContext(s.slice(s.indexOf('payload:')+8,s.indexOf('update:',s.indexOf('payload:'))).trim().replace(/,$/,''),{currentSampling:()=>({steps:77,cfg:14})});};
const response = (job,events=[['done',{image:'/image',seed:123}]]) => new Response(events.map(([e,d])=>`event: ${e}\ndata: ${JSON.stringify(d)}\n\n`).join(''),{headers:{'X-Gen-Job':job}});
async function run(method,shot,fetcher,p=()=>({})) {let idle;const ended=new Promise(r=>idle=r);const calls=[];globalThis.fetch=async (u,o)=>{calls.push([u,o]);return fetcher(u,o,calls.length);};const gen=createGenerator({payload:p,update(){},idle});gen[method](shot);await ended;return calls;}
test('fresh enqueue discards a retained terminal job and transient progress',async()=>{const shot={positive:'x',seed:123,job:'old',progress:.9,netFail:true,result:{old:true},live:true,_savedJob:'old'};const calls=await run('enqueue',shot,()=>response('new'));assert.equal(calls[0][0],'/api/gen');assert.equal(calls[0][1].method,'POST');assert.equal(shot.job,'new');assert.equal(shot.netFail,false);assert.equal(shot.live,false);});
test('explicit resume attaches retained job',async()=>{const calls=await run('resume',{positive:'x',job:'old'},()=>response('old'));assert.equal(calls[0][0],'/api/gen/attach?job=old&since=0');});
test('disconnected fresh request reattaches with replay offset',async()=>{const calls=await run('enqueue',{positive:'x'},(u,o,n)=>n===1?response('new',[['queued',{prompt_id:'p'}]]):response('new'));assert.equal(calls[0][0],'/api/gen');assert.equal(calls[1][0],'/api/gen/attach?job=new&since=1');});
test('server failure retry starts a new request',async()=>{const shot={positive:'x'};await run('enqueue',shot,()=>response('failed',[['error',{error:'bad'}]]));assert.equal(shot.status,'failed');const calls=await run('enqueue',shot,()=>response('retry'));assert.equal(calls[0][0],'/api/gen');});
for(const file of ['web6/app.js','web6/fuse.js']) {
 test(file+' request uses saved sampling independent of panel',async()=>{const calls=await run('enqueue',{positive:'x',seed:1,sampling:{steps:19,cfg:4}},()=>response('x'),payload(file));assert.equal(JSON.parse(calls[0][1].body).steps,19);assert.equal(JSON.parse(calls[0][1].body).cfg,4);});
 test(file+' legacy sampling uses server defaults',async()=>{const calls=await run('enqueue',{positive:'x'},()=>response('x'),payload(file));assert.equal(JSON.parse(calls[0][1].body).steps,undefined);});
 test(file+' heat toggle sequence recomputes automatic weights',()=>{const ctx={settings:sanitizeSettings({heats:['tease']},data),data,sanitizeSettings,toggleHeat,weightsForHeats,saveSettings(){},writeJ(){},FK:{},retrial(){},renderAll(){},renderCase(){},renderRating(){},renderPool(){},renderRules(){},renderLibrary(){},renderGoBar(){},renderLibraryChrome(){},renderGoFloat(){},pool:new Set(),lex:{},lib:{byTag:new Map()},hand:{update(){}},refreshStamps(){},syncPoolFlags(){}};const change=evaluate(file,'setSettings',ctx);for(const heat of ['flash','tease','sex','mixed']){const next=toggleHeat(ctx.settings.heats,heat);change({heats:next});assert.deepEqual(JSON.parse(JSON.stringify(ctx.settings.weights)),weightsForHeats(next,data.heatWeights));}});
}
test('shot persistence includes sampling and active hires sampling',()=>{store.saveShots([{id:'s',sampling:{steps:19,cfg:4},hi:{job:'h',status:'running',mode:'deep',scale:2,sampling:{steps:23,cfg:5,denoise:.3}}}]);const saved=store.loadShots()[0];assert.deepEqual(saved.sampling,{steps:19,cfg:4});assert.deepEqual(saved.hiresJob.sampling,{steps:23,cfg:5,denoise:.3});});

test('mochi makeShot snapshots sampling at creation',()=>{let panel={steps:17,cfg:3};const ctx={SECTION_ORDER:[],lib:{byTag:new Map()},currentTriggerText:()=>'',weightPositive:(p)=>p,insertTriggerAfterCast:s=>s,currentLorasPayload:()=>[],currentCkpt:()=>'',currentWorkflowId:()=>'',currentSampling:()=>({...panel}),shotSeq:1,settings:{}};const make=evaluate('web6/app.js','makeShot',ctx);const shot=make({positive:'x',sections:{}},1,new Set());panel={steps:70,cfg:9};assert.deepEqual(JSON.parse(JSON.stringify(shot.sampling)),{steps:17,cfg:3});});
test('fuse print creation persists frozen sampling',()=>{let panel={steps:17,cfg:3};let saved;const node={scrollTo(){}};const ctx={recordUses(){},tagsOfPositive:()=>[],lib:{byTag:new Map()},trials:[{positive:'x',mine:[],letter:'A'}],picked:0,sigOf:()=>'',printFor:()=>null,comfyOk:true,printSeedOf:()=>1,isFixedSeed:()=>false,trialPositive:(t)=>t.positive,insertTriggerAfterCast:s=>s,currentTriggerText:()=>'',settings:{},currentLorasPayload:()=>[],currentCkpt:()=>'',currentWorkflowId:()=>'',currentSampling:()=>({...panel}),bed:{pins:[],carried:{}},seeds:[],prints:[],PRINT_MAX:80,renderLine(){},generator:{enqueue(){}},savePrints(){},$:()=>node,reduced:()=>true,renderPreview(){},renderTrials(){},renderPrintBar(){},rollPress(){},sfx:{roll(){}},haptic(){},announce(){}};evaluate('web6/fuse.js','printNow',ctx)();panel={steps:70,cfg:9};evaluate('web6/fuse.js','savePrints',Object.assign(ctx,{writeJ:(k,v)=>saved=v,FK:{prints:'p'},S:store}))();assert.deepEqual(JSON.parse(JSON.stringify(saved[0].sampling)),{steps:17,cfg:3});const loaded=evaluate('web6/fuse.js','loadPrints',Object.assign(ctx,{readJ:()=>saved.map(p=>({...p,status:'done'}))}))();assert.deepEqual(JSON.parse(JSON.stringify(loaded[0].sampling)),{steps:17,cfg:3});});
test('queued hires task captures mode sampling before request and persists it',async()=>{let panel={steps:22,cfg:5,denoise:.3};const hires=await moduleOf('web6/hires.js',`const el=()=>{}; const currentHiresSampling=()=>globalThis.hiresPanel(); const createGenerator=h=>globalThis.hiresGenerator(h);\n`);globalThis.hiresPanel=()=>({...panel});let genHooks,queued;globalThis.hiresGenerator=h=>{genHooks=h;return{enqueue:t=>queued=t};};const runner=hires.createHires({update(){}});const target={positive:'x',image:'/base',width:1024,height:1024};runner.start(target,'deep',2);panel={steps:77,cfg:14,denoise:.9};assert.deepEqual(genHooks.payload(queued).hires,{mode:'deep',scale:2,image:'/base',steps:22,cfg:5,denoise:.3});queued.job='h';genHooks.update(queued);assert.deepEqual(store.hiresJobOf(target).sampling,{steps:22,cfg:5,denoise:.3});});

test('mochi same-seed reprint posts a fresh job with frozen sampling',async()=>{let fresh;const node={getBoundingClientRect:()=>({top:0})};const ctx={noteUses(){},shotSeq:2,shots:[],shotNode:()=>node,flip:(n,f)=>f(),$:()=>({prepend(){}}),enter(){},innerHeight:800,trimWall(){},S:{saveShots(){}},generator:{enqueue:s=>fresh=s},renderGoBar(){}};evaluate('web6/app.js','reprint',ctx)({id:'old',status:'done',job:'oldjob',positive:'x',seed:42,sampling:{steps:19,cfg:4}});const calls=await run('enqueue',fresh,()=>response('new'),payload('web6/app.js'));assert.equal(calls[0][0],'/api/gen');const body=JSON.parse(calls[0][1].body);assert.equal(body.seed,42);assert.equal(body.steps,19);});
test('fuse retry posts a fresh job preserving original seed and sampling',async()=>{let fresh;const ctx={generator:{enqueue:s=>fresh=s},savePrints(){}};const shot={status:'failed',job:'oldjob',positive:'x',seed:42,sampling:{steps:19,cfg:4}};evaluate('web6/fuse.js','reprint',ctx)(shot);const calls=await run('enqueue',fresh,()=>response('new'),payload('web6/fuse.js'));assert.equal(calls[0][0],'/api/gen');assert.equal(JSON.parse(calls[0][1].body).steps,19);assert.equal(JSON.parse(calls[0][1].body).seed,42);});
test('real queued hires request uses snapshot after the panel changes',async()=>{let panel={steps:22,cfg:5,denoise:.3};globalThis.hiresPanel=()=>({...panel});globalThis.hiresGenerator=createGenerator;const hires=await moduleOf('web6/hires.js','const el=()=>{}; const currentHiresSampling=()=>globalThis.hiresPanel(); const createGenerator=h=>globalThis.hiresGenerator(h);\n');let release;const held=new Promise(r=>release=r);let finish;const completed=new Promise(r=>finish=r);const calls=[];globalThis.fetch=async(u,o)=>{calls.push([u,o]);if(calls.length===1)await held;return response('h'+calls.length);};let done=0;const runner=hires.createHires({update(){},done(){if(++done===2)finish();}});const t=()=>({positive:'x',image:'/base',width:1024,height:1024});runner.start(t(),'deep',2);runner.start(t(),'deep',2);panel={steps:77,cfg:14,denoise:.9};release();await completed;assert.equal(calls.length,2);assert.equal(JSON.parse(calls[1][1].body).hires.steps,22);assert.equal(JSON.parse(calls[1][1].body).hires.denoise,.3);});
test('hires resume restores saved sampling and attaches the original job',async()=>{globalThis.hiresPanel=()=>({steps:77,cfg:14});globalThis.hiresGenerator=createGenerator;const hires=await moduleOf('web6/hires.js','const el=()=>{}; const currentHiresSampling=()=>globalThis.hiresPanel(); const createGenerator=h=>globalThis.hiresGenerator(h);\n');let finished;const done=new Promise(r=>finished=r);const calls=[];globalThis.fetch=async(u,o)=>{calls.push([u,o]);return response('old');};const t={positive:'x',image:'/base',width:1024,height:1024};hires.createHires({update(){},done:finished}).resume(t,{job:'old',mode:'deep',scale:2,sampling:{steps:22,cfg:5,denoise:.3}});await done;assert.equal(calls[0][0],'/api/gen/attach?job=old&since=0');assert.deepEqual(t.hires.sampling,{steps:22,cfg:5,denoise:.3});});
